#!/bin/sh

#
# Perform the weekly backups.
#

SCRIPT_PATH="`dirname "$0"`"

# This performs all backups.
"${SCRIPT_PATH}/execute-group" weekly

# This rotates and prunes backup archives.
"${SCRIPT_PATH}/rotate-backups"
