#!/bin/sh

#
# Backup manager script by Brad Conte for managing a set of test actions.
#

# ==============================================================================
# Setup
# ==============================================================================

cd "`dirname "$0"`"
source ../config/manager.functions


# ==============================================================================
# Main Program
# (Save relevant stuff to pwd)
# ==============================================================================

# Include this dummy backup as a sanity test so that we can tell after the fact
# if the basics were working.
execute_action test-action
archive_action test-action

execute_action MyAnimeList.net
archive_action MyAnimeList.net

execute_action arch-linux-config
archive_action arch-linux-config
