#!/bin/sh

#
# Backup script by Brad Conte for backing up a personal resource.
# This backs up: Nothing, it is a test script.
#

# ==============================================================================
# Setup
# ==============================================================================

# Execute global functionality and import global function resources.
source ../config/global.functions


# ==============================================================================
# Main Program
# (Save relevant stuff to cwd)
# ==============================================================================

# This script does nothing.
# Has side-effect of giving us a timestamp from the last time the test script
# was executed.
echo "Test backup contents." > "$BACKUP_DIR/test-file"
cat "$BACKUP_DIR/test-file"
